name: Daily Trending Repo Creator

on:
  schedule:
    - cron: "0 3 * * *"
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  create-trending-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run auto repo creator
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: python3 auto_repo.py

      - name: Commit activity log
        run: |
          git config user.name "kushagrabansal-IOT"
          git config user.email "kushagrabansal94@gmail.com"
          git add daily_log.txt || true
          git diff --staged --quiet || git commit -m "log: Daily automation run $(date +'%Y-%m-%d %H:%M')"
          git push || true
